name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy_web:
    name: Export Web
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Web
      uses: gamedrivendesign/docker-godot-export@gh-action
      with:
        export-template: HTML5
        output-filename: index.html
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output

  deploy_server:
    name: Export Server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: gamedrivendesign/docker-godot-export@gh-action
      name: Build Server
      with:
        export-template: ServerWebsockets
        output-filename: server
    - uses: appleboy/ssh-action@master
      env:
        USER: ${{ secrets.USERNAME }}
        REPO: ${{ github.event.repository.name }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        envs: USER,REPO
        key: ${{ secrets.KEY }}
        script: |
          mkdir -p "/home/$USER/godot-servers/$REPO"
    - uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: ./output/*
        target: /home/${{ secrets.USERNAME }}/godot-servers/${{ github.event.repository.name }}
        strip_components: 1
    - uses: appleboy/ssh-action@master
      env:
        USER: ${{ secrets.USERNAME }}
        REPO: ${{ github.event.repository.name }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        envs: USER,REPO
        script: |
          cd "/home/$USER/godot-servers/$REPO"
          ../Godot_v3.4.2-stable_linux_headless.64 --main-pack server.pck &

